POST http://localhost:8080/api/editions/1/products/3/preferences
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNTQyMzA4MTc3LCJleHAiOjE1NDI5MTI5Nzd9.CM1tdNOegPOqcEo4a1yoTwtXstfNStluBt1LILZ014s9Vhga-A_F8GeMgQtE4XJ3eiX8Oydor74QjqKEUdmSpQ

< updatePreference.json
###