GET http://localhost:8080/api/users/1
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQxNzk3Mzg2LCJleHAiOjE1NDI0MDIxODZ9.mSJ909aHzbrAJ4cJfh9l3QmAEcMTACmhKHWVv93sfkPF9HBAiTfwY0E2xJ2ztZv_Phz0eKk3Af0Pi5W1XzTGpg

###
