POST http://localhost:8080/api/editions/1/publish
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQ0MDUyMjk1LCJleHAiOjE1NDQ2NTcwOTV9.WsSN1TY5ZeDPqBUIScyDI_dcrUtLOaWXu4r0deCwZkN4JrzrJBC7I4d3obYRBwfid_LCWVSkTP0wGiVgAEhKxg

###
