POST http://localhost:8080/api/editions/1/items
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQyOTA3Nzc3LCJleHAiOjE1NDM1MTI1Nzd9.PA7CF35w5Sgk8CaU3QEEoEKTxLSEyUL7HneRDWrPPjUTK3sXobLWM2CBMsQyRmJdWZ5iiqlLI6sd4M_SgkZ3pA

< createItem.json

###
