PUT http://localhost:8080/api/users/me/password
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNTM3NzEzOTUwLCJleHAiOjE1MzgzMTg3NTB9.FVq0EJA4voghQazKLgCd51JzrVHGaqyJXgmFIf9kkqeoowAayzUEqjxBBCp78s5HQD7_HsKgMbOK4i4LI-4IqA

< changePassword.json

###