POST http://localhost:8080/api/editions
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQwNTcwMzA2LCJleHAiOjE1NDExNzUxMDZ9.rV6EsR9Okckxiu7uMFtuEbVHY0RNGISdDcr0aim2hFUWTvoxVHBJfBZFf1he3hhmPZZXRUe03sgnhT9W_OJ9_Q

< createEdition.json

###
   #
   ####