POST http://localhost:8080/api/products
Content-Type: Application/Json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQwMTIwNTg2LCJleHAiOjE1NDA3MjUzODZ9.Un2ue5IMBmx7Dle_exPsyt7WlmDNEpQTdpBOZCAoraaJDP2iEK4HiGl9Ip1fG0x1Jd8gAOePunb9TLu4aeH7qg

< createProduct.json

###
