DELETE http://localhost:8080/api/products/2/images/a1_2_2018-10-22-20-04-42-409.gif
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQwMTIwNTg2LCJleHAiOjE1NDA3MjUzODZ9.Un2ue5IMBmx7Dle_exPsyt7WlmDNEpQTdpBOZCAoraaJDP2iEK4HiGl9Ip1fG0x1Jd8gAOePunb9TLu4aeH7qg

###
