PUT http://localhost:8080/api/products/2
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNTQwNDg3NjM4LCJleHAiOjE1NDEwOTI0Mzh9.6hH3f5xXmEEd4NHsayaFnwKzh7ezsIkHkhnCa0F8PKDDuxYhH-7Mvd6ZXGdvmk4lvaSFnXGCiU9kNYxxagrWxQ

< editProduct.json

###