PUT http://localhost:8080/api/editions/2
Content-Type: Application/Json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTMzNjY4NTg3LCJleHAiOjE1MzQyNzMzODd9.OETxJkoFc1o45u_9mk6J7mKGbgKZIxi4pnsAi9j3cRDH1KGy0IC0BAf4YEG2wS6xQyWqXGsyH2b5fMT1SNPLEQ

< editEdition.json

###