GET http://localhost:8080/api/editions
Content-Type: Application/Json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTM3NzA4MzM4LCJleHAiOjE1MzgzMTMxMzh9.4T_ENi6IzO6y1LU7IMF9h3IeUzeuoflQrpFmRfjEFHNb8hbuLsViHwR6_Q6sOEPyiFagzQf7sp21BPcTnxEFLg

###
