GET http://localhost:8080/api/users/me
Content-Type: Application/Json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNTM5Mjg2NzQxLCJleHAiOjE1Mzk4OTE1NDF9.A5euL7VpqlWbQwUZ5Sng6CvA3YCWbaW2QGuX-4UZSfVOxCHVOfvrIuZy00ac_n5m17WFljMycgdC59NxgaWG9Q

###