GET http://localhost:8080/api/users/me
Content-Type: Application/Json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQwMTQ2NDEwLCJleHAiOjE1NDA3NTEyMTB9.JOkbY6Aij97M36CGBPI5j2QvabtoOnWydRJ2i7q_GaAAa-ug-D0FoBgosca98AQtrVuhKE9XlNGdav17V3AyhA

###