GET http://localhost:8080/api/editions/2/products
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2IiwiaWF0IjoxNTQxNTIyMTczLCJleHAiOjE1NDIxMjY5NzN9.kMmrWCHkVsWvi3hLzpICvQy_iY1j_ji_6OWNAxsOadooCrfoPMbGWHDzNZOZBDZVJdB8a6p4LLMtqSslFGejCQ

###
