GET http://localhost:8080/api/users/2
Content-Type: Application/Json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNTM4NDI0MDg1LCJleHAiOjE1MzkwMjg4ODV9.YwYCdCFyuk4SWx7hGdBmtALtymw1s6dqcOA-ftIGwS5-pt4mb5l3Sc0aKa2rGr1kYZnut_Yk5H2jnAjDiQqWfg

###
