POST http://localhost:8080/api/editions/3/users
Content-Type: Application/Json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNTM5MDIyMjM5LCJleHAiOjE1Mzk2MjcwMzl9.WjnG8cQcw1v9ACd1sFVfyuibzlyf2APxatUSibwXPf3sOZhtyPlUzCw0WMqOyQtjANQRoDNAjauDgAmsu6HGRw

###
