POST http://localhost:8080/api/editions/3/participants
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNTQwODQ3NTcyLCJleHAiOjE1NDE0NTIzNzJ9.wsn-vb4qOA5GlL7YPfTIo7T2Wv1K1L8Hst9h9aajFIpN0f9zV9wJSqhRvDQpDfYIzLFSKuGG-gPW6xZtXRu6hQ

###
