POST http://localhost:8080/api/editions/2/moderators
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQxNTA0NzQxLCJleHAiOjE1NDIxMDk1NDF9.JD5jOmJoN4foP5CAGANMqL45TC2X1E4UqIksUP5OzN4zjBShceSIRdyJcK55i7LM5gIchlQGExiXlnZQmXyJgg

< makeUserEditionModerator.json

###