POST http://localhost:8080/api/editions/1/products
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNTQyMDQwMDM3LCJleHAiOjE1NDI2NDQ4Mzd9.mFZV9r88yJ93QCgOPacMiONXFgpY5EXU3TDtT-gwToAKvvWZC5rp7A2LY13END2YuMgooQt-1WxymcobE6aq6g

< createProduct.json

###
