PUT http://localhost:8080/api/users/me/password
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNTQyMTIzNTQzLCJleHAiOjE1NDI3MjgzNDN9.xksQ-BRAfa0Xp_YIcTy30VB_SKEhZ8FwChfyfRI3GA6_eXUzC9Hg_jxZvSaYlJeQ9gfJSj_GQ3EpwNbcZdFSgw

< changePassword.json

###