PUT http://localhost:8080/api/users/me
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQzNTE5NDA0LCJleHAiOjE1NDQxMjQyMDR9.QOaJIia9wSIGn2REINEqQGJHD462KHy4sv5sFuOboIHEcKHgth3ZwoOnufOxq4a1yDdQpihu1vMIxvndY2v7Bg

< editMe.json

###