GET http://localhost:8080/api/users/me
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQyMTIyOTUwLCJleHAiOjE1NDI3Mjc3NTB9.kNHus5aDYkrANMcOfkuGnD9GLX9vy5j7GxNr9n8TGiMr029XQHvSGnFVJhDBvx1hBwFGMWhdoCI3nuiwYHMIRg

###