GET http://localhost:8080/api/users/2
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQyOTE5MzU2LCJleHAiOjE1NDM1MjQxNTZ9.zsMM5CBlHrHablcjlZJcu4Nk1Aics0LkKIPG2xSmt337qfbClFL9g-rEYnPiHXzjJhlrsG2bEQ6NKAzIXf9v1w

###
