POST http://localhost:8080/api/editions
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQyMzg3NDUyLCJleHAiOjE1NDI5OTIyNTJ9.6tDyxLEda9L3FtpAHSX80BByUBDFkzJdElBDL65V-n7dpzRTjqwFFVJcQJGEPvi1XkH5Tw37d6N2T4u1zrQyvg

< createEdition.json

###
   #
   ####