POST http://localhost:8080/api/editions
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQ0MDM4MTExLCJleHAiOjE1NDQ2NDI5MTF9.wBG52A6lSkEGZox3IkCDXzDZJLGfE5f536MiUnh0IvFeGNn-xLjx3m97zL0WKzViZx_Be72gYvg77tDUibAB2A

< createEdition.json

###
   #
   ####