PUT http://localhost:8080/api/editions/1
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQzODMyMTk0LCJleHAiOjE1NDQ0MzY5OTR9.TWjAyIqek_dtktqPOIKgTfETn2NyAoWRyXD5zMZup7EiSlLYbyWR_75MDyyq_Q5d9txhuZh0t-PrbNp6q1IREw

< editEdition.json

###
