GET http://localhost:8080/api/editions
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNTQzODM3MjA3LCJleHAiOjE1NDQ0NDIwMDd9.dfr3Hhg3Pb-DMKwRac0TPfFyLnqR976ZCSW5JSEKXjuKhX-WDNVip-qYXRbX4K2dn2Xj-o4x5dqC74o1lEswQg

###
