POST http://localhost:8080/api/editions/1/participants
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNTQyMzA4MDcyLCJleHAiOjE1NDI5MTI4NzJ9.180Bu8xxzwsOOXaj0poMuAYvPiArewo3hZJ89ooXlrrdowVTgb-KlwOXnjUEVCsaM7iP4deipF7EBINfbCWj1A


###
