GET http://localhost:8080//api/moderator-requests/my
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNTQyMjM2NDQ1LCJleHAiOjE1NDI4NDEyNDV9.eVun3sFLeZ7zRChzd1GEIAuxGNgYYOiGzaMJPqphgQh5ztEztYO4crk6vVZqG7PRrnL29a8692ihB0eUDLBYfA

###
   #
   ####