GET http://localhost:8080//api/moderatorRequests
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNTMzNjczODU3LCJleHAiOjE1MzQyNzg2NTd9.AMcj8U9WVgG1XAFjjehBMN4LkNXLlGS_QPdiDRRVCPZ3b1DHY90LBluowMQmZHyYacmSOUxryOP7OTBDQM3Pww

###
   #
   ####