GET http://localhost:8080/api/moderator-requests
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQyMjMzMzMzLCJleHAiOjE1NDI4MzgxMzN9.pr53dI8cYqC5KLIvGfAcSqPGTQCHq3jza-hJB2tRMAQFmOjG6v8VA4uZ8pHPZKINSQ79o38H_WBvKqmSgl4F1w

###
   #
   ####