GET http://localhost:8080/api/moderator-requests
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTQ0MDQzODE0LCJleHAiOjE1NDQ2NDg2MTR9.xiK_QqGqouwyhDQzToMxBlhll3XW2i3CWyNDEgadgETWeEkbv8xt4Hoz2O0BXcWwwDAwClfCxK5aigyTSxXZfA

###
   #
   ####