POST http://localhost:8080/api/moderator-requests
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNTQyMjM2NTgyLCJleHAiOjE1NDI4NDEzODJ9.YCNSv2rISliMLoWw8czVrW0_STTMmnJ5l4DYr0jqs1XSmfAV5y8BKSkxC809esso2QgtDGIF55BjSGfPQhWCzQ

< requestModerator.json

###
   #
   ####