POST http://localhost:8080/api/moderator-requests
Content-Type: Application/Json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxNDgiLCJpYXQiOjE1NDQwNDM3ODUsImV4cCI6MTU0NDY0ODU4NX0.vh4aXLCWXv36VTbHUAJ-0Yok7gIF7hcRAe6dwq21jimvNKeHz-2WwZvw3x8yKLUfL5bfndIHXu5doyjzsneYXg

< requestModerator.json

###
   #
   ####